### ISSUE TITLE
TypeId exported from typings but not from the module

### ISSUE THREAD

**Issue by PachowStudios** [brianc/node-pg-types#116]
```ts
import { TypeId } from 'pg-types';
```

This returns undefined even though `index.d.ts` says it's exported.

**Comment by bendrucker** [comment]
PR welcomed, my experience with TS is limited so I don't plan to chase this down.

**Comment by brt-han-mai** [comment]
@PachowStudios : If you are still insisted to use this package, you can go with `builtins` instead of `TypeId`. My problem is with bigint string where I can use `builtins.INT8`. But then I recognize that I can directly use `20` without the package at all.
@bendrucker : at least remove/or don't export the unfinished code, please. Thanks.

**Comment by bendrucker** [comment]
If someone would like to fix this I'd appreciate it. I don't use TypeScript and am not well qualified to review it. I asks for tests and do my best to sanity check. Clearly there is some disconnect here because `TypeId` was never part of the library, it was just added to the TS file in #83.

Nastiness will not tolerated. Issue is locked, but a PR is very welcome and I'd be happy to help any TypeScript user willing to tackle it.
